version: '3.1'
services:
  java:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: openjdk:11
    ports: 
      - 5005:5005
      - 8080:8080
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pizza_delivery
      MYSQL_DATABASE: pizza_delivery
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
